name: Build Android APK

on:
  push:
    tags:
      - "v*"   # contoh: v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Init Bubblewrap project
        run: |
          bubblewrap init --manifest=https://erdrop.vercel.app/manifest.json --skipPwaValidation --skipSigning
          bubblewrap build --skipSigning

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./app-release-signed.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
