name: Build Android APK

on:
  push:
    tags:
      - 'v*'     # dijalankan setiap push tag versi, misalnya v1.0.0
  workflow_dispatch:

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bubblewrap CLI
        run: npm install -g @bubblewrap/cli

      - name: Build APK using Bubblewrap
        run: |
          bubblewrap init --manifest=https://erdropmanager.vercel.app/manifest.json --skipPwaValidation --skipSigning
          bubblewrap build --skipSigning

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app-release-unsigned.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
